name: Test Workflow

on:
  workflow_dispatch:
  
env:
  FOO: bar
  ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
  
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps: 
      - name : First step
        run: echo ${{ env.ACTIONS_RUNNER_DEBUG }}
        
      - name: Second step
        run: echo ${{ env.FOO }} && return 1
      
