name: Test Workflow

on:
  workflow_dispatch:
  
env:
  FOO: bar
  ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
  
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps: 
      - name : Check debug status
        if: ${{ env.ACTIONS_RUNNER_DEBUG == 'true' }}
        run: echo "VERBOSE= --verbose" >> $GITHUB_ENV
        
      - name: Second step
        run: echo ${{ env.VERBOSE }} && return 1
      
